### ISSUE TITLE
typo which causes missing title

### ISSUE THREAD

**Issue by anoymouserver** [Freifunk-Hennef/ffhef-fw-dl#2]
https://github.com/Freifunk-Hennef/ffhef-fw-dl/blob/master/firmware.php#L331
`["lang_title"]` should be `["lang_titel"]`

**Comment by Drasek** [comment]
Fixed in commit: https://github.com/Freifunk-Hennef/ffhef-fw-dl/commit/6b9ffb435134bfa9d7ec08c2747e9df62becfc20
