### ISSUE TITLE
Liste der Modelle bleibt leer

### ISSUE THREAD

**Issue by poldy79** [Freifunk-Hennef/ffhef-fw-dl#4]
vielen Dank, dass Du Dir die Mühe gemacht hast, so einen Downloader zu schreiben. 

Ich habe versucht das für Stuttgart aufzusetzen:
https://firmware.freifunk-stuttgart.de/downloader/index.php

Allerdings bleibt die Liste der Modelle leer. 

Wahrscheinlich liegt es daran, wie unsere FIrmwrare-Dateien heißen:
Factory: gluon-ffs-tp-link-tl-wdr4300-v1.bin
Sysupgrade: gluon-ffs-0.7+2016.03.31-22.24-g.b704308-s.b00a7b1-tp-link-tl-wdr4300-v1-sysupgrade.bin

Einstiegspunkt: http://firmware.freifunk-stuttgart.de/gluon/

Du weißt sicher besser, wo wir rein greifen müssen, damit das auch bei uns funktioniert. 

Viele Grüße aus Stuttgart
Leonard

**Comment by Drasek** [comment]
Der Downloader erwartet zur Zeit Dateinamen, die gleich anfangen, bzw. um genau zu sein die gleiche Länge haben vor dem Namen des Herstellers, in deinem Fall unterscheidet sich die Länge ja deutlich.

Siehe: gluon-ffs- / tp-link-tl-wdr4300-v1.bin = 10 Zeichen
und gluon-ffs-0.7+2016.03.31-22.24-g.b704308-s.b00a7b1- / tp-link-tl-wdr4300-v1-sysupgrade.bin = 51 Zeichen

Ich kann das anpassen und für jede Kombination Entwicklungsstadium/(factory/sysupgrade) die Länge einzeln bestimmen, gib mir ein paar Tage dafür, dann melde ich mich mit einer Lösung zum testen!

**Comment by Drasek** [comment]
Wobei ich da glaube mittlerweile ein Array verwende - kannst Du mir Deine community-config einmal zumailen, damit ich da rein schauen kann, bitte? Das grundsätzliche Verzeichnis findet er und hat auch Zugriff, sonst würde ein Fehler ausgegeben...

**Comment by poldy79** [comment]
Hi,

u.U. kann ich auch unsere Dateinamen anpassen. Mir war nur nicht klar, woran es scheitert. 

Ich liefere Dir noch unsere Community-Datei, versuche das mit der Anpassung und dann schauen wir noch mal. 

Gruß 
Leonard

**Comment by Drasek** [comment]
Vielleicht probierst Du es mit den Dateinamen einfach mal aus, indem Du nur ein paar Dateien verwendest und den Rest woanders hin backupst. Verwende dafür möglichst TP-Link Geräte, da er die Position des Herstellers im String über die Suche nach "tp-link" herausfindet (TP-Link war einfach hier die Wahl, da die praktisch immer unterstützt werden von Gluon in allen Versionen).

**Comment by poldy79** [comment]
So mache ich das. Melde mich wieder

Caspar Armster <notifications@github.com> schrieb am Di. 15. Nov. 2016 um
08:42:

**Comment by poldy79** [comment]
Das Community-File sieht folgendermaßen aus:

https://gist.github.com/poldy79/0ad110ba3193d9c80c5429da40a81741

**Comment by Drasek** [comment]
Hast Du es einmal mit einem abschliessenden "/" probiert beim "download_path"? also:
`"download_path" => "../gluon/",`

**Comment by poldy79** [comment]
das war es. Habe mich von " Warning: × Warning! Unbekannten Hersteller im Dateinamen gefunden, bitte Script updaten! (index.html)" total verwirren lassen und hatte das beim testen gleich wieder rückgängig gemacht. Wer lesen kann ist klar im Vorteil. 

Mal schauen, welche Hersteller wir unterstützen, die noch nicht im config.inc.php haben. Oder was könnte ihn noch verwirren. Wenn ich in der config.inc.php nur die Stable habe, kommt die Meldung 2x.

**Comment by poldy79** [comment]
Ah - wir generieren index.html-Dateien... unsere bisherigen Download-Tabellen. 

Habe das so gelöst:

                if ($files[$entwicklung[$i]][$installation[$j]][$x] == "index.html")
                {
                }
                else if(isset($router_tmp[$x]['hersteller']) != true) {
                    $error_text[$err]="Unbekannten Hersteller im Dateinamen gefunden, bitte Script updaten! (".$files[$entwicklung[$i]][$installation[$j]][$x].")";
                    $err++;

Ich mache das issue mal zu...

**Comment by Drasek** [comment]
Es gibt eine Stelle weiter oben wo ich alles was "manifest" heisst rauswerfe, dort könnte man auch ".html" grundsätzlich weg filtern:

```
                            $pos = stripos($files[$entwicklung[$i]][$installation[$j]][$x], 'manifest');
                            if($pos !== false) {
                                array_splice($files[$entwicklung[$i]][$installation[$j]], $x, 1);
                                $x--;
                                $file_count--;
                            }
```
den gleichen Abschnitt kopieren und "manifest" durch ".html" ersetzen und direkt danach einfügen in die Schleife:

```
                            $pos = stripos($files[$entwicklung[$i]][$installation[$j]][$x], '.html');
                            if($pos !== false) {
                                array_splice($files[$entwicklung[$i]][$installation[$j]], $x, 1);
                                $x--;
                                $file_count--;
                            }
```
